### ISSUE TITLE
compile with gcc 4.8.2

### ISSUE THREAD

**Issue by laplasz** [gpakosz/Assert#6]
Hi there!

I am trying to use your simple static_assert macro found on this site:
http://pempek.net/articles/2013/11/23/boost-static-assert-without-boost/
It is working with gcc 4.3.4

However I tied with 4.8.2 and got the following:
```
error: expected \ufffd\ufffd\ufffd)\ufffd\ufffd\ufffd before \ufffd\ufffd\ufffd,\ufffd\ufffd\ufffd token
 STATIC_ASSERT(false, "no_you_cant_have_a_pony");
error: expected unqualified-id before numeric constant
 STATIC_ASSERT(false, "no_you_cant_have_a_pony");
error: \ufffd\ufffd\ufffd__static_assertion_at_line_\ufffd\ufffd\ufffd was not declared in this scope
 STATIC_ASSERT(false, "no_you_cant_have_a_pony");
error: invalid use of incomplete type \ufffd\ufffd\ufffdstruct JOIN\ufffd\ufffd\ufffd
 STATIC_ASSERT(false, "no_you_cant_have_a_pony");
error: forward declaration of \ufffd\ufffd\ufffdstruct JOIN\ufffd\ufffd\ufffd
 STATIC_ASSERT(false, "no_you_cant_have_a_pony");
error: template argument 1 is invalid
 STATIC_ASSERT(false, "no_you_cant_have_a_pony");
error: invalid type in declaration before \ufffd\ufffd\ufffd(\ufffd\ufffd\ufffd token
 STATIC_ASSERT(false, "no_you_cant_have_a_pony");
error: typedef \ufffd\ufffd\ufffdJOIN\ufffd\ufffd\ufffd is initialized (use decltype instead)
error: \ufffd\ufffd\ufffd__static_assertion_test_at_line_\ufffd\ufffd\ufffd was not declared in this scope
 STATIC_ASSERT(false, "no_you_cant_have_a_pony");
```
Do you have some simple static_assert code which is working on 4.8.2 - any idea what could be the problem?
Thanks in advance!
Balazs

**Comment by gpakosz** [comment]
Can you check the encoding of your source file? There's no reason it would break with any version of GCC as far as I know.

**Comment by gpakosz** [comment]
Also if you're targeting C++11 or above there's [`static_assert` in the standard](http://en.cppreference.com/w/cpp/keyword/static_assert).

**Comment by gpakosz** [comment]
Well if you use `-std=c++11` then my code is useless.

As for your problem, `\ufffd` is Unicode replacement character and I don't understand why your GCC is saying that.

**Comment by laplasz** [comment]
ok, now I used another shell, and got the following: 
```
error: expected ‘)’ before ‘,’ token
 STATIC_ASSERT(false, "no_you_cant_have_a_pony");
```
the code is:
```
#ifndef VERSION_1
STATIC_ASSERT(false, "no_you_cant_have_a_pony");
#endif
```

**Comment by gpakosz** [comment]
Ok now I understand.

Either you target C++11 and above and use `static_assert` from the standard and do:

```
static_assert(false, "no you can't have a pony");
```

Either you target C++98 and then the code from my site is relevant. However, as explained in the article:

> The only restriction is that **message has to be a valid C++ identifier**: you need to separate words with e.g. underscores and it cannot start with a digit.

And you do:
```
STATIC_ASSERT(false, no_you_cant_have_a_pony);
```

What's happening is that you're mixing the two and the compiler complains.

**Comment by laplasz** [comment]
ok, thanks  - my big mistake.
But once I defined a const and use in the macro still I got the error:
```error: expected ‘)’ before ‘,’ token
 STATIC_ASSERT(false, version);```

the code is:
```const int version = 6;
#ifndef VERSION_1
STATIC_ASSERT(false, version);
#endif```

can you give me an example with a good identifier? as you can see, I am not an expert..
thanks in advance! I would use static_assert() but the project have to use C++98

**Comment by gpakosz** [comment]
I don't understand what you're trying to achieve. Please paste your full example and GCC output.

Nevertheless, `STATIC_ASSERT(false, whatever)` will always produce a compile time error.
